name: Push Docs to the Academy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
    # Note: If nothing under docs/ changes, the workflow will not run even on main.

jobs:
  push-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: Jahia/github-to-academy@v1
        with:
          files: docs/**/*.md
          graphql-endpoint: ${{ secrets.ACADEMY_ENDPOINT }}
          graphql-authorization: ${{ secrets.ACADEMY_AUTHORIZATION }}
